version: "3.5"

services:
  api01: &api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api01
    environment:
      - PORT=8082
    ports:
      - "8082:8082"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.37"
          memory: "30MB"
    networks:
      - app-network

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.37"
          memory: "30MB"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"
    networks:
      - app-network

  db:
    image: postgres:latest
    hostname: db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
      #- ./config/postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: "0.56"
          memory: "480MB"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U admin -d rinha'" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - app-network

networks:
  app-network: