version: "3.5"

services:
  api01: &api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api01
    environment:
      - PORT=8081
    network_mode: host
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.37"
          memory: "30MB"

  api02:
    <<: *api
    hostname: api02
    network_mode: host
    environment:
      - PORT=8082
    deploy:
      resources:
        limits:
          cpus: "0.37"
          memory: "30MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

  db:
    image: postgres:latest
    hostname: db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    network_mode: host
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
      #- ./config/postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: "0.56"
          memory: "480MB"
